version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3308/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge